### ISSUE TITLE
Is it possible to add args to commands in chain?

### ISSUE THREAD

**Issue by jesseleite** [jisaacks/ChainOfCommand#1]
Is it possible to add args to commands in chain?

**Comment by jisaacks** [comment]
Sorry I did not answer sooner, I just noticed this.

To answer your question, yes.

In the read me example:

``` python
window.run_command("chain",{"commands":[["focus_group",{"group":0}]]})
```

The commands array is

``` json
[
  ["focus_group",{"group":0}]
]
```

the `"focus_group"` is the command, and the `{"group":0}` are the arguments.

**Comment by jesseleite** [comment]
:O Thanks!
