### ISSUE TITLE
Not working in Debian

### ISSUE THREAD

**Issue by T04435** [jisaacks/ChainOfCommand#5]
Hello there I install the plugin and try to use it  but it seems not to do anything. these are my commands so far:
`{
  "keys": ["ctrl+alt+shift+d"], 
  "command": "duplicate_file", 
  "args": {
    "commands": [
      ["select_all"],
      ["copy"],
      ["new_file"],
      ["paste"],
      ["save"]
    ]
  }
},
{
  "keys": ["ctrl+alt+f"], 
  "command": "autoindent_file", 
  "args": {
    "commands": [
      ["select_all"],
      ["reindent"]
    ]
  }
}`

**Comment by ahuff44** [comment]
You seem confused about how the sublime-keymap file works. You can't define new commands like "duplicate_file", you can only run already-existing commands, like "chain":
See this example from the README:
```
{
  "keys": ["super+shift+option+d"], 
  "command": "chain", 
  "args": {
    "commands": [
      ["select_all"],
      ["copy"],
      ["new_file"],
      ["paste"],
      ["save"]
    ]
  }
}
```

So your "autoindent_file" key binding should be this instead:
```
{
  "keys": ["ctrl+alt+f"], 
  "command": "chain", 
  "args": {
    "commands": [
      ["select_all"],
      ["reindent"]
    ]
  }
}
```

**Comment by T04435** [comment]
I fixed it while ago but forgot about this issue.
